// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1ZsHKbrt39F2DfBReug4kyxqm3ftBu6o',
    appId: '1:576897046653:web:37b65c1381721e09dc3914',
    messagingSenderId: '576897046653',
    projectId: 'smarttrafficai-3b436',
    authDomain: 'smarttrafficai-3b436.firebaseapp.com',
    storageBucket: 'smarttrafficai-3b436.firebasestorage.app',
    measurementId: 'G-H6XNVYGH47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRO-aAulPBMxwzZ6Sb2zFaFcoNq31AwNs',
    appId: '1:576897046653:android:51ceae6b5701321bdc3914',
    messagingSenderId: '576897046653',
    projectId: 'smarttrafficai-3b436',
    storageBucket: 'smarttrafficai-3b436.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjcksgWXiXhdXUCRZsHqauV2nBKzkKRlQ',
    appId: '1:576897046653:ios:359b3e6447885e72dc3914',
    messagingSenderId: '576897046653',
    projectId: 'smarttrafficai-3b436',
    storageBucket: 'smarttrafficai-3b436.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjcksgWXiXhdXUCRZsHqauV2nBKzkKRlQ',
    appId: '1:576897046653:ios:359b3e6447885e72dc3914',
    messagingSenderId: '576897046653',
    projectId: 'smarttrafficai-3b436',
    storageBucket: 'smarttrafficai-3b436.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1ZsHKbrt39F2DfBReug4kyxqm3ftBu6o',
    appId: '1:576897046653:web:4329701b19211158dc3914',
    messagingSenderId: '576897046653',
    projectId: 'smarttrafficai-3b436',
    authDomain: 'smarttrafficai-3b436.firebaseapp.com',
    storageBucket: 'smarttrafficai-3b436.firebasestorage.app',
    measurementId: 'G-9J2MBWLHTS',
  );
}
